
package test.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetNameServiceImplService", targetNamespace = "http://impl.service/", wsdlLocation = "http://localhost:9000/count?wsdl")
public class GetNameServiceImplService
    extends Service
{

    private final static URL GETNAMESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETNAMESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GETNAMESERVICEIMPLSERVICE_QNAME = new QName("http://impl.service/", "GetNameServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/count?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETNAMESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GETNAMESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GetNameServiceImplService() {
        super(__getWsdlLocation(), GETNAMESERVICEIMPLSERVICE_QNAME);
    }

    public GetNameServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETNAMESERVICEIMPLSERVICE_QNAME, features);
    }

    public GetNameServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GETNAMESERVICEIMPLSERVICE_QNAME);
    }

    public GetNameServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETNAMESERVICEIMPLSERVICE_QNAME, features);
    }

    public GetNameServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetNameServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetNameService
     */
    @WebEndpoint(name = "GetNameServiceImplPort")
    public GetNameService getGetNameServiceImplPort() {
        return super.getPort(new QName("http://impl.service/", "GetNameServiceImplPort"), GetNameService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetNameService
     */
    @WebEndpoint(name = "GetNameServiceImplPort")
    public GetNameService getGetNameServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service/", "GetNameServiceImplPort"), GetNameService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETNAMESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GETNAMESERVICEIMPLSERVICE_EXCEPTION;
        }
        return GETNAMESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
