
package test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetNameService", targetNamespace = "http://service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetNameService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getName")
    @WebResult(partName = "return")
    @Action(input = "getName", output = "http://service/GetNameService/getNameResponse")
    public String getName(
        @WebParam(name = "name", partName = "name")
        int name);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getRandomName")
    @WebResult(partName = "return")
    @Action(input = "getRandomName", output = "http://service/GetNameService/getRandomNameResponse")
    public String getRandomName();

}
