spring:
  application:
    name: consumer

dubbo:
  protocol:
    name: dubbo
    port: -1
  scan:
    basePackages: org.eva
  application:
    name: consumer-demo
  registry:
    address: nacos://192.168.3.7:8848
    username: nacos
    password: nacos